
version: '3.8'

services:
  prestamype-exchange-api:
    container_name: prestamype-exchange-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_URI=mongodb://mongo:27017/prestamype
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: prestamype-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: prestamype
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
