
version: '3.8'

services:
  prestamype-exchange-api:
    container_name: prestamype-exchange-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_URI=mongodb://mongo:27017/prestamype
      - MONGO_DB=prestamype
      - MAILER_HOST=smtp.gmail.com
      - MAILER_PORT=465
      - MAILER_USER=
      - MAILER_PASS=
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: prestamype-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: prestamype
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: prestamype-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    restart: unless-stopped

volumes:
  mongo_data:
